################ NETWORKS ################
networks:
  deafult:
    driver: bridge
  docker_socket_network: # Firewall network for containers that need access to docker socket
    name: docker_socket_network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  gluetun_network:
    name: gluetun_network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

################ SECRETS ################
secrets:
  basic_auth_credentials:
    file: $DOCKERDIR/secrets/basic_auth_credentials
  cf_dns_api_token:
    file: $DOCKERDIR/secrets/cf_dns_api_token
  guacamole_postgres_password:
    file: $DOCKERDIR/secrets/guacamole_postgres_password
  guacamole_postgres_user:
    file: $DOCKERDIR/secrets/guacamole_postgres_user
  openvpn_clientcrt:
    file: $DOCKERDIR/secrets/openvpn_clientcrt
  openvpn_clientkey:
    file: $DOCKERDIR/secrets/openvpn_clientkey
  twitch_key:
    file: $DOCKERDIR/secrets/twitch_key
  youtube_key:
    file: $DOCKERDIR/secrets/youtube_key

################ SERVICES ################
# PREFIX bgon = Bird Gardens Of Naples
# HOSTNAME = bgon - defined in .env
include:
# CORE
  - compose/$HOSTNAME/socket-proxy.yml
  - compose/$HOSTNAME/traefik.yml
  - compose/$HOSTNAME/dozzle.yml

# VPN & REMOTE ACCESS
  - compose/$HOSTNAME/gluetun.yml
  # - compose/$HOSTNAME/guacd.yml
  # - compose/$HOSTNAME/guacamole.yml

# STREAMING
  # - compose/$HOSTNAME/obs.yml