services:
  dozzle: # Real-time Docker Log Viewer
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    # depends_on:
    #   - gluetun
    user: $PUID:$PGID
    # network_mode: "service:gluetun"
    networks:
      - proxy_network
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
