services:
  gluetun: # VPN
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - $DOCKERDIR/appdata/gluetun:/gluetun
    networks:
      - proxy_network
    ports:
      - 3000:3000/tcp # Homepage
    secrets:
      - openvpn_clientcrt
      - openvpn_clientkey
    environment:
      VPN_SERVICE_PROVIDER: airvpn
      VPN_TYPE: openvpn
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      UPDATER_PERIOD: 12h
      OPENVPN_KEY: /run/secrets/openvpn_clientkey
      OPENVPN_CERT: /run/secrets/openvpn_clientcrt
      FIREWALL_VPN_INPUT_PORTS: 80,443,3000,14550
      SERVER_COUNTRIES: United States
