services:
  guacd: # Remote Desktop Server
    image: ghcr.io/linuxserver/guacd:latest
    container_name: guacd
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - postgres
    #   gluetun:
    #     condition: service_healthy
    # network_mode: "service:gluetun"
    networks:
      - guacamole_network
    volumes:
    - $DOCKERDIR/appdata/guacd/drive
    - $DOCKERDIR/appdata/guacd/record
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
