services:
  homepage: # Application Dashboard
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/homepage:/app/config
    network_mode: "service:gluetun"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID