services:
  postgres: # Database
    image: postgres
    container_name: postgres
    security_opt:
      - no-new-privileges:true
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    volumes:
      - $DOCKERDIR/appdata/postgres/init:/docker-entrypoint-initdb.d:ro
      - $DOCKERDIR/appdata/postgres/data:/var/lib/postgresql/data:rw
    secrets:
      - guacamole_postgres_user
      - guacamole_postgres_password
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: /run/secrets/guacamole_postgres_password
      POSTGRES_USER: /run/secrets/guacamole_postgres_user